defaults:
  - process: process2           ### esto enlaza config con procces2, las config estan vinculadas
  - model: model1
  - _self_

raw:
  path: data/raw/raw.csv

processed:
  dir: data/processed
  X_train:
    name: X_train.csv
    path: ${processed.dir}/${processed.X_train.name}
  X_test:
    name: X_test.csv
    path: ${processed.dir}/${processed.X_test.name}
  y_train:
    name: y_train.csv
    path: ${processed.dir}/${processed.y_train.name}
  y_test:
    name: y_test.csv
    path: ${processed.dir}/${processed.y_test.name}

final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}

model:
  dir: models
  name: xgboost
  path: ${model.dir}/${model.name}


mlflow_tracking_ui: https://dagshub.com/DaniJorCa/Innotech.mlflow
mlflow_user: DaniJorCa
mlflow_api: 79b0db6014a166ac90731acbb94489b1e7110dcb
experiment: "MLOps-e2e"
repo_url: https://dagshub.com/DaniJorCa/Innotech